name: Github actions demo
run-name: Testing our basic Github actions workflow

on: [push]
env:
#  owner_name: Prudhvi 
  reason:  simply
jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is execution as part of the new workflow triggered by $repo_owner trigger reason is $reason"

