name: Github actions demo
run-name: Testing github actions with variables

on: [push]
env:
#  owner_name: Prudhvi 
  reason:  simply
  owner_repo: ${{ vars.repo_owner }}
jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is execution as part of the new workflow triggered by $owner_repo trigger reason is $reason"

