name: Event triggered this workflow
run-name: Checking the workflow reusabilty
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  fork:
    branches:    
      - main 
env:
  owner_name: Prudhvi
  owner_full_name: ${{ vars.REPO_OWNER }}
  my_secret_var_value: ${{ secrets.MY_SECRET }}
jobs:
  reuse_job: 
    uses: ./.github/workflows/reuse_job.yml
  main_job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo " Hello, this job is triggered by $owner_name and his full name is $owner_full_name and my secret is $my_secret_var_value" 
  
